services:
  mongodb:
    container_name: mongo.back
    hostname: mongodb
    command: --replSet=RS
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="db_orders"
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      rs-local-network:

  mongo-init:
    image: mongo:latest
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      rs-local-network:
    command: >
      sh -c "sleep 5; mongosh --host mongodb:27017 --eval '
      rs.initiate( {
         _id : \"RS\",
         members: [
           { _id: 0, host: \"localhost:27017\" }
         ]
       })
      '"

  redis:
    container_name: redis.back
    ports:
    - 6379:6379
    hostname: redis.back
    image: redis:6.2.7
    volumes:
      - redis:/data
    restart: on-failure
    networks:
      rs-local-network:

volumes:
  redis:
  mongo:

networks:
  rs-local-network:
   name: rs-local-network
